### ISSUE TITLE
comment utiliser sans docker

### ISSUE THREAD

**Issue by dba59** [fmartinou/teleinfo-mqtt#14]
bonjour
est il possible de faire tourner ce code sans docker parce que sous buster pas de docker ( ou plus de docker)
si oui une quels sont les pre-requis

merci d'avance

**Comment by fmartinou** [comment]
Bonjour,

Je ne comprends pas pourquoi il ne serait pas possible d'installer Docker sur burster ? ([toujours dans la liste des distributions supportées](https://docs.docker.com/engine/install/debian/)) ?

Quoi qu'il en soit...

La seule solution officielle supportée est l'image Docker mais il est tout à fait possible de le faire tourner directement sur node.js soi-même (mais je ne fournirai pas de support).

### Procédure
1. Installer [Node.js](https://nodejs.org/en/)
2. Cloner [le dépôt Github](https://github.com/fmartinou/teleinfo-mqtt)
3. Sous /app, installer les dépendances `npm ci`
4. Sous /app, exécuter le script index.js en prenant soin de positionner [les variables d'environnement attendues par l'application](https://fmartinou.github.io/teleinfo-mqtt/#/configuration/)

Ex: `SERIAL="/dev/ttyUSB1" MQTT_URL="mqtt://localhost:1883" node index.js`
