### ISSUE TITLE
EDF Zen Plus

### ISSUE THREAD

**Issue by cob94440** [fmartinou/teleinfo-mqtt#20]
Hello I have EDF zen plus and the addon detect base tarif. Not HP or HC.
I Have wednesday, saturday and sunday where HP are at HC cost.
And rest of time 12h30-15h30 HC and 03h00-08h00 HC.
What is wrong?

**Comment by cob94440** [comment]
![image](https://user-images.githubusercontent.com/62489067/160134851-4d91ec29-60ea-4b92-b5f8-65363fa2cf70.png)

**Comment by cob94440** [comment]
Tu as une idée de pourquoi le tarif est en TH? Toutes heures.

**Comment by fmartinou** [comment]
Les propriétés remontées via mqtt sont directement les étiquettes trouvées dans les trames reçues.

Donc j'imagine que la trame reçue a pour valeur BASE pour l'étiquette OPTARIF.

Je vais regarder la spécification teleinfo en mode historique mais il se peut que ton abonnement zen plus ne soit pas supporté par la spec.

**Comment by fmartinou** [comment]
La spec

https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.enedis.fr/media/2035/download&ved=2ahUKEwj-5cSE24z3AhXCyYUKHbcdCf8QFnoECAMQAQ&usg=AOvVaw0Bn9Pv64VK2dhbtmrZD8YD

**Comment by fmartinou** [comment]
Ça semble être les infos remontées par le compteur qui sont en cause.

https://forum.gce-electronics.com/t/eco-device-avec-abonnement-mes-jours-zen/13764/2

**Comment by cob94440** [comment]
Visiblement le dernier message indique que la personne est passé en standard

**Comment by fmartinou** [comment]
Je ne connais pas la procédure pour passer le compteur en mode standard ; enedis doit-il intervenir ?

teleinfo2mqtt n'est pas encore compatible avec le mode standard mais c'est en cours.

**Comment by cob94440** [comment]
C'est un simple appel à mon fournisseur et ils font la demande a enedis.
J'ai vu sur jeedom que ça remonte davantage d'informations.
Sur mon linky je vois bien les différentes périodes HP/hc. A savoir
qu'après la complexité c'est que le mercredi et le weekend ça reste des
HP/hc mais les HP sont au tarif hc. Et le reste de la semaine c'est le
classique HP/hc

**Comment by cob94440** [comment]
De ce que j'ai comme info les différences sont le nom du mode et la vitesse qui est a 9600 bauds
