### ISSUE TITLE
mode standard

### ISSUE THREAD

**Issue by palouf34** [fmartinou/teleinfo-mqtt#24]
Bonjour,

Le mode standard ne semble pas fonctionné.

`
15:54:30.851 ERROR teleinfo-mqtt: Corrupted data received [J$LJKjQkz1EFZuRj*#$P@jJ$J$Be{oB@1k$TH!VVVVVVVr)H1@1GKc0J4RJj4CJj4SJjTSKb4J	K$WaEFDR(Kq@j]
15:54:35.185 ERROR teleinfo-mqtt: Corrupted data received [$J$B{oB1{mT$!VVVFVVVVr)H1B1W!KcJ4bJj4JJj4JJjPSKb0J	K$GaAZuRjKq@jJ$J`$%{oB1k@T!VVFVVVVV}r)H1S1W!	cJ4SJZJ4SKJTSKJSkJK*QkzQAFDZuRjK$q@jJ$J0%1oBk@X!VVVVVVVVr)H1R1WKc0J4pJjSJjSJjtJKBJK$uaAFDZuRj*$q@jj$$B{-B1kiT0!VVVVVVVVri1fc*4SKJ4JJjtJJJQJbJKKTWaDZuRjK$q@jJJ$%{oB=!VFVVVWVVV}r)N1S1W!	cJ4SJj4SJj4S]
15:54:37.797 ERROR teleinfo-mqtt: Corrupted data received [jtSKbJKK$WaEFZuR*K$J@jJ$J$B%{o1+T!VVVVVVVFVr	1S1G*Kc0J4rJj4AJj4SJjTSKbJ	K$vaAVDZuRjKq@jJ$J$BC{oB1{}T!VVVVVVVVVr)H1S1W!K4SKJ4SKJ4CJtSKJ4SkJKKdkza(DZRjK$q@JdJ$%{oBk@TXVVVVVVVVVV{RH1S1W!]
15:54:38.238 ERROR teleinfo-mqtt: Corrupted data received [cJSJ*PJJjQJJJ4Sk	K$W!EFZuR*K$@j]
15:54:40.632 ERROR teleinfo-mqtt: Corrupted data received [$J$B%{oB1kTX!VFVVVVVVr	DH1S1G!Ka0J4pJj4SJjtJJJUJKbJKK$vaEFDZuRjKq@j$J4$BCB{gB1{%Td!VVVFVVVVFVr)H1c1w!KcJ4SJj4SJjSJ(J4SkK4k`EFDZuRjKR$q@jJAJ$B%[o1kX!VVVVVVVVVr)H1CB\!Jj4S]
15:54:42.856 ERROR teleinfo-mqtt: Corrupted data received [j4SJjSJjpSKb0J	K$WaEDZujKq@(J$Zb$BkR{oB1k@T!VVVVVVVVr)H1S1d!	cJSJjSJ(JKBJ4SkKKEkzaZ+KRj+$q1jJ$JB%!oB1kT!VVVVVVVVFVr)H1S1WKc4J4rJj4vJj4@JjtSKbJK$WaEFDZuRjK$q@]
15:54:47.186 ERROR teleinfo-mqtt: Corrupted data received [QJK@KKEkza<DJRj$q@jJ$J$BzR{oBk@X!VVFVVVVVVr)BPlBJjtJJjSJjS]
15:54:49.026 ERROR teleinfo-mqtt: Corrupted data received [jtSbJKKdkzaAFDZuRj$@jJ$J$Bco1kTX!VVVVFVVVr)1SW!	cJ4SJJ4SKJTSKJSkJK(k`DAFZuRjK$@jJ$JB%{oBkX!VFVVVVVVV)H1SW!cJ4SJJQJJj4S]
15:54:49.076 ERROR teleinfo-mqtt: Corrupted data received [jtS]
15:54:49.828 ERROR teleinfo-mqtt: Corrupted data received [bJK+Pkza,DJ`

voici un extrait du log.

pensez vous pouvoir mettre en place cette fonctionnalité ?

**Comment by fmartinou** [comment]
Bonjour,

Le mode standard est en cours d'implémentation.
L'issue qui y est consacrée est ici : https://github.com/fmartinou/teleinfo-mqtt/issues/16

Je ferme cette issue en faveur de l'autre du coup.
