### ISSUE TITLE
Version 7.0.0 : segmentation fault

### ISSUE THREAD

**Issue by Bobdugrand8** [fmartinou/teleinfo-mqtt#27]
Depuis la mise à jour en 7.0.0 le plugin Home Assistant ne démarre plus.
```

22:04:35.007  INFO teleinfo-mqtt: Connecting to port [/dev/ttyUSB0] with history TIC mode
Segmentation fault (core dumped)
```

Je suis sur OrangePi PC Plus ( armv7).

**Comment by ripp2003** [comment]
Same problem since the update. Already try to uninstall and reinstall but, Segmentation fault.
I'm on pi 3

**Comment by fmartinou** [comment]
Thank you for reporting this issue.
I'm closing It in favor of #26 (cause duplicate).
